language: python

# python versioning 
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

# requirements
install: 
  - pip install -r requirements.txt

# environments to use for tests (below)
env: 
  - TEST_DIR=cmap/cmapPy/pandasGEXpress/tests
  - TEST_DIR=cmap/cmapPy/set_io/tests

# run all tests in each test dir 
script: cd $TEST_DIR && python -m unittest discover -p "test_*.py"

# what branches of github to use
branches:
  only:
    - master
